### ISSUE TITLE
correct implicits?

### ISSUE THREAD

**Issue by fommil** [Spinoco/fs2-http#14]
following the example at https://github.com/Spinoco/fs2-http#http-client and using the 8 lines of imports I am getting

```
could not find implicit value for parameter AG: java.nio.channels.AsynchronousChannelGroup
[error]     http.client[Task]().flatMap { client =>
```

are you sure this is the full list of imports?

**Comment by fommil** [comment]
quickstart needs to include `Resources`

**Comment by pchlupacek** [comment]
just added this to Readme
