### ISSUE TITLE
SSL Handshake Issues

### ISSUE THREAD

**Issue by ChristopherDavenport** [Spinoco/fs2-http#29]
The `createSSLEngine` call fails to handshake properly for a lot of smaller websites. [Bug Location](https://github.com/Spinoco/fs2-http/blob/series/0.4/src/main/scala/spinoco/fs2/http/internal/internal.scala#L128)

This can be fixed by adding a reference to the host and port that is being secured. `sslContext.createSSLEngine(host, port)`

**Comment by pchlupacek** [comment]
@ChristopherDavenport thanks for reporting this.
